### ISSUE TITLE
messages Changes

### ISSUE THREAD

**Issue by wangroger0801** [chalmersfsd/cfsd-logic-lynx-state-machine#1]
**State machine part:**
Sender Stamps Changes:

CHANGES - > Before

  | 1405 | ebsFault | sensor | bool | StateM |  
  | 1401 | asState | sensor | states*[2] | StateM|

  | 1413 | steerFault | sensor | bool | StateM |  
  | 1414 | ebsState | sensor | 0-2*[2] | StateM |  
  | 1415 | serviceValve | sensor | bool | StateM |  

  | 1350 | brakeDutyCycle | req | dutyCycles | Brake | StateM

CHANGES - > After

  | 2105 | ebsFault | sensor | bool | StateM |  
  | 2101 | asState | sensor | states*[2] | StateM|

  | 2113 | steerFault | sensor | bool | StateM |  
  | 2114 | ebsState | sensor | 0-2*[2] | StateM |  
  | 2115 | serviceValve | sensor | bool | StateM |  

  |2150 | brakeDutyCycle | req | dutyCycles | Brake | StateM

Removed:
 | 1510 | brakeActual | sensor| | StateM      |

Message type Changes: 
 asReadyToDrive from opendlv::proxy::SwitchStateReading to 
 opendlv::proxy::SwitchStateRequest

**Comment by wangroger0801** [comment]
**messages Changes - CANgw**

Sender Stamps Changes:

CHANGES - > Before

| 1407 | resStatus | sensor | 0/1*[1] | CANgw
| 1408 | resEStop | sensor | 0/128*[1] | CANgw
| 1409 | resQuality | sensor | 0-100*[1] | CANgw
| 1410 | resButtons | sensor | 1/3/5/7*[1] | CANgw

| 1406 | asMission | sensor | 0-8 | CANgw

| 1416 | KnobR | sensor | 1-12 int | CANgw
| 1417 | NnobL | sensor | 1-12 int | CANgw

| 1404 | asReadyToDrive | sensor | 1/0 | StateM

|1099 | resInitialize | req | Don't Care*[1] | StateM

CHANGES - > After

| 1801 | resStatus | sensor | 0/1*[1] | CANgw
| 1802 | resEStop | sensor | 0/128*[1] | CANgw
| 1803 | resQuality | sensor | 0-100*[1] | CANgw
| 1804 | resButtons | sensor | 1/3/5/7*[1] | CANgw

| 1906 | asMission | sensor | 0-8 | CANgw

| 1916 | KnobR | sensor | 1-12 int | CANgw
| 1917 | NnobL | sensor | 1-12 int | CANgw

| 1904 | asReadyToDrive | req | 1/0 | StateM

|1899 | resInitialize | req | Don't Care*[1] | StateM

Message type Changes:
asReadyToDrive from opendlv::proxy::SwitchStateReading to
opendlv::proxy::SwitchStateRequest

**Comment by wangroger0801** [comment]
**Messages changes - Torque Request Type and senderstamps**

BEFORE
opendlv::proxy::TorqueRequest
| 1503 | torqueRight | req | 0-2400cNm | StateM
  | 1502 | torqueLeft | req | 0-2400cNm | StateM
  | 1501 | torqueRight | req | 0-2400cNm | longCtrl
  | 1500 | torqueLeft | req | 0-2400cNm | longCtrl

AFTER


opendlv::cfsdProxy::TorqueRequestDual

|1910 | torqueLeft&torqueRight | req | 0-2400cNm | StateM | CANgw-Lynx
  | 2101 | torqueLeft&torqueRight | req | 0-2400cNm | longCtrl | StateM

**Comment by lowitz** [comment]
Pushed test version with extended message set
